version: '3.8'

services:
  # Flask Application
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./data/ml_models:/app/data/ml_models
      - ./data/sqlite:/app/data/sqlite
      - ./data/contracts:/app/data/contracts
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///data/sqlite/app.db
      - GANACHE_URL=http://ganache:8545
      - CHAIN_ID=1337
      - ML_MODEL_PATH=/app/data/ml_models/duration_predictor.h5
    depends_on:
      - ganache

  # Ganache Blockchain (Using official Docker image)
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    volumes:
      - ./data/ganache:/ganache_data
    command:
      - --server.host=0.0.0.0
      - --chain.chainId=1337
      - --chain.networkId=1337
      - --database.dbPath=/ganache_data
      - --wallet.deterministic=true
      - --wallet.totalAccounts=10
      - --wallet.defaultBalance=1000
      - --miner.blockTime=0
      - --chain.hardfork=london
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  ml_models:
    driver: local
  sqlite_data:
    driver: local
  ganache_data:
    driver: local
  contract_data:
    driver: local

networks:
  default:
    driver: bridge
